### ISSUE TITLE
Make it compatible with eclipse

### ISSUE THREAD

**Issue by debugger22** [kikoso/Swipeable-Cards#1]
It would be very good if we can make it work with ADT.

**Comment by thewthew** [comment]
has someone created the eclipse project ? 

Thanks a lot !

**Comment by AndroidDeveloperLB** [comment]
@thewthew Sadly, Eclipse&ADT are now deprecated by Google, so everyone (including me) are moving to Android-Studio.
If you wish to import the project to Eclipse, it's usually just by renaming the "java" folder to "src", or taking its sub folder up, and then renaming it to "src".
