### ISSUE TITLE
(Enhancement) Dynamically add cards to the back of the stack

### ISSUE THREAD

**Issue by eugeneli** [kikoso/Swipeable-Cards#14]
Hi, nice library! I think it would be cool if the library had support for adding new cards to the back of the card stack to create a "infinite" cards effect as new cards can be dynamically added. I made some modifications to the library that'll let me do that but it's a bit hacky.

**Comment by TiagoGouvea** [comment]
I'm waiting too. Please @eugeneli, share it!

**Comment by obsd** [comment]
so do I @eugeneli
