### ISSUE TITLE
1st CardModel item is always the same.

### ISSUE THREAD

**Issue by dannyroa** [kikoso/Swipeable-Cards#20]
I always get the same CardModel hence the same card always get the Click event. (https://github.com/kikoso/Swipeable-Cards/blob/master/AndTinder/src/main/java/com/andtinder/view/CardContainer.java#L449).

The card is being removed from the container (https://github.com/kikoso/Swipeable-Cards/blob/master/AndTinder/src/main/java/com/andtinder/view/CardContainer.java#L472)
but it seems that it is not being removed from the CardStackAdapter because the "pop" method is not being called anywhere.

Am I missing something?

**Comment by arjs1000** [comment]
@hackathoner I ended up migrating to the following library instead: https://github.com/Diolor/Swipecards/

This library seems more stable and maintainable. Feel free to check out my implementation of this here: https://play.google.com/store/apps/details?id=com.paywithvelocity.velocity

However, if you wish to still use this library. I managed to fix some of the problems by ensuring the parent card adapter class was correctly overriding its methods.

**Comment by davidm06** [comment]
dears any update ?

**Comment by kikoso** [comment]
This issue is solved with the latest update.

**Comment by monishagarwal215** [comment]
Kikoso i found that no where you are calling pop method, nor the adapter is empty it remains of same size.
