### ISSUE TITLE
Only the cardDimissedListener for the latest card runs for all subsequent cards!

### ISSUE THREAD

**Issue by t27** [kikoso/Swipeable-Cards#25]
I have made cardDimissedListeners for 2 different cards, with different outcomes on like and dislike. But when I am running the app, only the listener for the latest card on the stack is running for both the cards.

I put a dummy card without a listener as the latest card and no listener ran for any of the other cards.

For example, in the first card(named Card1) in the onLike(), I am printing(toast), "I liked card 1" and in the second I am printing "I liked card 2" but when I like(swipe in the like direction) both I get "I liked card1". 

Is the behaviour meant to be like this, ie. the onLike and onDislike listeners for the first card will run all the time? Ideally I would want to have different listeners for different cards?
Please enlighten me in this regards.
Thanks!

**Comment by kikoso** [comment]
This issue is solved with the latest update.
