### ISSUE TITLE
Can't run an eclipse for this one i got error

### ISSUE THREAD

**Issue by SakthivelA** [kikoso/Swipeable-Cards#29]
Hi, I try to run your project i get this error.

 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.andtinder.demo/com.andtinder.demo.MainActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class com.andtinder.view.CardContainer.

And also I am confusing to used for this one  compile project(':AndTinder'), include 'AndTinder', please help.

**Comment by achinverma** [comment]
i am getting the same error in eclipse, can you tell me how to fix this one ?
