### ISSUE TITLE
Binary XML file line #8: Error inflating class com.andtinder.view.CardContainer.

### ISSUE THREAD

**Issue by sathizmca** [kikoso/Swipeable-Cards#33]
Hi, I try to run your project i get this error.

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.andtinder.demo/com.andtinder.demo.MainActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class com.andtinder.view.CardContainer.

And also I am confusing to used for this one compile project(':AndTinder'), include 'AndTinder', please help.

**Comment by mottto** [comment]
clean the main liabrary project 
add liab to project add liab project in java build path in project tab 
clean your project . dont change style file . add android-support-v7-appcompat as liab in your project.
