### ISSUE TITLE
Getting name or details of card which is swiped

### ISSUE THREAD

**Issue by faisalmemon1991** [kikoso/Swipeable-Cards#34]
I am not able to get the details of the card which is swiped. I always get first item in below code

cardModel.setOnCardDimissedListener(new CardModel.OnCardDimissedListener() {
                @Override
                public void onLike(CardModel cardModel) {
                    Log.d(TAG,"Inner "+cardModel.getTitle() + " : ");
                }
                @Override
                public void onDislike(CardModel cardModel) {
                    Log.d(TAG,"Inner dislike "+cardModel.getTitle());
                    //adapter.pop();
                }
            });

**Comment by davidm06** [comment]
Hello
did you succeed ? I need the same as well and I do not finf
thanks
david

**Comment by faisalmemon1991** [comment]
I moved to a better library - https://github.com/Diolor/Swipecards

**Comment by davidm06** [comment]
dear sir

many thanks, I will probably move as well.
is it better to configure / use / design ?
thanks
david

**Comment by faisalmemon1991** [comment]
Yes it has been good till now :)

**Comment by davidm06** [comment]
dear
one more question, i dowloaded the library, my question is :
wich directory should I put in wich project directory ?
thanks

**Comment by faisalmemon1991** [comment]
I have used gradle for this.

But I think you should try copying it in Libraries folder.

**Comment by davidm06** [comment]
thanks
i understand Gradle is able to download on its own, right ? a little the 
same way as "Ubuntu Market" ?

David Marchioni,
Photographe,

Visitez mon site
www.davidmarchioni.fr <www.davidmarchioni.fr>

**Comment by kikoso** [comment]
This issue is solved with the latest update
