### ISSUE TITLE
Example for Fragment integration would be nice

### ISSUE THREAD

**Issue by stephanlindauer** [kikoso/Swipeable-Cards#36]
Hi there,
i am struggeling to integrate Swipeable-Cards in my application as part of a Fragment. Is that even possible? If yes, it would be nice to see an example of how thats supposed to be set up.
cheers!

**Comment by kikoso** [comment]
Hello @stephanlindauer ,

The library has been designed as a view, so you can integrate it in a fragment. If there is any particular issue you are facing feel free to write here.
