### ISSUE TITLE
Error when compiling with MavenCentral dependency

### ISSUE THREAD

**Issue by kokaz** [kikoso/Swipeable-Cards#41]
Gradle throws this error when trying to compile the project.

```
Error:(7, 9) Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:7:9
  	is also present at TeleBuzz.libs.Swipeable-Cards:AndTinder:unspecified:12:9 value=(@drawable/ic_launcher)
  	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:5:5 to override
```

**Comment by kikoso** [comment]
Hello @kokaz ,

That means Swipeable Cards is including a second icon, which actually is better if it is not done (a library does not need an icon).

Until I can get time to upload a new version, however, you can do what the error says and add 'tools:replace="android:icon" to use your own.
