### ISSUE TITLE
Cannot use android:icon when using this library

### ISSUE THREAD

**Issue by Nayar** [kikoso/Swipeable-Cards#47]
In my AndroidManifest.xml, i have
```
<application
        android:allowBackup="true"
        android:logo="@drawable/logofooter"
        android:icon="@drawable/logoappsico"
```
After importing the library, i get the following error:

Error:(20, 9) Attribute application@icon value=(@drawable/logoappsico) from AndroidManifest.xml:20:9
Error:(20, 9) Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@drawable/logoappsico) from AndroidManifest.xml:20:9
  	is also present at timdair:AndTinder:unspecified:12:9 value=(@drawable/ic_launcher)
  	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:17:5 to override

**Comment by kikoso** [comment]
@Nayar if you read the last line:

Suggestion: add 'tools:replace="android:icon"' to element at AndroidManifest.xml:17:5 to override

**Comment by Nayar** [comment]
did it like that. did not work
```
    <application
        android:allowBackup="true"
        android:logo="@drawable/logofooter"
        android:icon="@drawable/logoappsico"
        android:label="@string/app_name"
        android:theme="@style/AppTheme"
        tools:replace="android:icon">
```

Finally removed the icon from AndroidManifiest from AndTinder. Seems to work now

**Comment by gPinato** [comment]
I have the same problem, I also used the replace="android:icon" and It didn't work.

**Comment by MuhammadZahab** [comment]
add tools:replace="android:icon" in your app manifest not in Library manifest
