### ISSUE TITLE
Crash on Some Devices while Swiping the Cards

### ISSUE THREAD

**Issue by sirajsumra92** [kikoso/Swipeable-Cards#52]
I am getting these issue with the Library while testing on Samsung Galaxy Core on Intercept Touch Event:

04-13 17:28:05.252: E/AndroidRuntime(2549): java.lang.IllegalArgumentException: pointerIndex out of range
04-13 17:28:05.252: E/AndroidRuntime(2549): at android.view.MotionEvent.nativeGetAxisValue(Native Method)
04-13 17:28:05.252: E/AndroidRuntime(2549): at android.view.MotionEvent.getX(MotionEvent.java:2145)

Getting issue in Intercept Touch Event in following code in container:
case MotionEvent.ACTION_MOVE:
pointerIndex = event.findPointerIndex(mActivePointerId);
x = event.getX(pointerIndex);
y = event.getY(pointerIndex);

Can anyone please help me with these issue.

**Comment by dorinsimina** [comment]
Check the method findPointerIndex which might return -1. In that case the line x = event.getX(pointerIndex); will throw an error.

**Comment by kikoso** [comment]
Solved
