### ISSUE TITLE
Dynamically populating the cards

### ISSUE THREAD

**Issue by lmouhib** [kikoso/Swipeable-Cards#55]
I am fetching pictures from a server and need to put them in cards, but i don't know how many of them i have, its done dynamically, how can i proceed, I have no clue. thanks

**Comment by ImTosS** [comment]
When you get your images from your server, you may have something like an ArrayList or a String[] pictures array, this is an example:

ArrayList<String> picturesArrayList = new ArrayList<String>();
picturesArrayList.add("http://www.thehealthygamer.com/wp-content/uploads/2012/06/Diablo-3-Monk.jpg");
picturesArrayList.add("http://www.thehealthygamer.com/wp-content/uploads/2012/06/Diablo-3-Monk.jpg");
picturesArrayList.add("http://www.thehealthygamer.com/wp-content/uploads/2012/06/Diablo-3-Monk.jpg");
//This is where you contain all your images "picturesArrayList"
//Define your SimpleCardStackAdapter as a class attribute.
SimpleCardStackAdapter simpleCardStackAdapter;
//Initialise it in your activity or fragment
simpleCardStackAdapter = new SimpleCardStackAdapter(context);
for(String pictureArrayElement : picturesArrayList ){
simpleCardStackAdapter.add(new CardModel("Title goes here", "Description goes here", pictureArrayElement));
}
//Add again the adapter has a fix to prevent drag and drop issues
cardContainer.setAdapter(simpleCardStackAdapter);

Hope it helps :)

**Comment by sushilblore** [comment]
@ImTosS .. In your solution, still all the images needs to be downloaded beforehand. Is there a solution possible to pick images dynamically from server when the cards are swiped?

**Comment by ImTosS** [comment]
@sushilblore Yeah, is actually the same procedure, Let´s suppose that you have an ApiClient object that is the one used to make a request to your server, and you have a method that do a specific request to get images.
<pre>
ArrayList<PictureDTO> arrayListPicturesDTO = apiClient.getImagesFromServer();  
</pre>
In your method "getImagesFromServer()" is where you get a JSON response from server, now you have to iterate that JSON (or JSON Array) and set a pictureDTO for each JSON in order to get an ArrayList<PictureDTO> with your data. After that you just iterate as in example above.
<pre>
for(PictureDTO pictureDTO : arrayListPicturesDTO ){
    simpleCardStackAdapter.add(new CardModel("Title goes here", "Description goes here", pictureDTO.getUrl()));
}
</pre>
I can recommend you <a href="https://github.com/koush/ion">Ion</a> or <a href="http://square.github.io/retrofit/">Retrofit</a> in order to make your request. Both of them have callbacks that fiils your "Model" or your "DTO" and returns a List<Object> ready to iterate in your adapter.

Hope it helps! :D

**Comment by goelvibhor4** [comment]
I used this code for (int k = 0; k < 10; k++) {
                    JSONObject post4 = list.optJSONObject(k);

                    FeedItem item = new FeedItem();
                    final String PostTitle= post4.getString("name");
                    final String PostDescription= post4.getString("description");
                    final String image= post4.getString("slider");


                    Log.d("title", PostTitle);
                    Log.d("image", image);


                    Bitmap mBitmap = Picasso.with(VContext).load(image).get();
                    final Drawable d = new BitmapDrawable(getResources(), mBitmap);

                    CardModel card = new CardModel(PostTitle,PostDescription,d);

                    card.setOnClickListener(new CardModel.OnClickListener() {
                        @Override
                        public void OnClickListener() {
                            Log.i("Swipeable Cards", "I am pressing the card");
                            Log.d("TITLE", PostTitle);

                        }
                    });


                    card.setOnCardDismissedListener(new CardModel.OnCardDismissedListener() {
                        @Override
                        public void onLike() {
                            Log.i("Swipeable Cards", "I like the card");
                           /* CardModel card = new CardModel(PostTitle, PostDescription, d);
                            adapter.add(card);*/
                        }

                        @Override
                        public void onDislike() {
                            Log.i("Swipeable Cards", "I dislike the card");
                         /*CardModel card = new CardModel(PostTitle, PostDescription, d);
                            adapter.add(card);*/
                        }
                    });


                    adapter.add(card);


                }
            }
        }

        catch (JSONException e) {
            e.printStackTrace();


        } catch (IOException e) {
            e.printStackTrace();
        }
    }

**Comment by lmouhib** [comment]
I used Ion and it worked fine, i changed the "cardImageDrawable" in the model with a string that hold url to my picturen thanks :)

**Comment by davidm06** [comment]
Hi Imouhib

I did not succeed in sending you an email directly
can yuo please help on this issue ?
thanks
David

**Comment by lmouhib** [comment]
Hello David,

I will share my code, just need to get a hand on it, probably tonight!

Best.

**Comment by davidm06** [comment]
thanks !!!!


2016-04-13 12:26 GMT+02:00 lmouhib <notifications@github.com>:

> Hello David,
>
> I will share my code, just need to get a hand on it, probably tonight!
>
> Best.
>
> On Wed, Apr 13, 2016 at 10:20 AM, davidm06 <notifications@github.com>
> wrote:
>
> > Hi Imouhib
> >
> > I did not succeed in sending you an email directly
> > can yuo please help on this issue ?
> > thanks
> > David
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/kikoso/Swipeable-Cards/issues/55#issuecomment-209327498
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/kikoso/Swipeable-Cards/issues/55#issuecomment-209358150>
>



-- 
http://www.davidmarchioni.fr
Photographe

**Comment by davidm06** [comment]
Hello sir

I'm sorry I'm not familiar with the Github website. I hope I will be mailed
when you will upload...
I do not want to miss that !

2016-04-13 13:01 GMT+02:00 david marchioni <david.marchioni@gmail.com>:

> thanks !!!!
>
>
> 2016-04-13 12:26 GMT+02:00 lmouhib <notifications@github.com>:
>
>> Hello David,
>>
>> I will share my code, just need to get a hand on it, probably tonight!
>>
>> Best.
>>
>> On Wed, Apr 13, 2016 at 10:20 AM, davidm06 <notifications@github.com>
>> wrote:
>>
>> > Hi Imouhib
>> >
>> > I did not succeed in sending you an email directly
>> > can yuo please help on this issue ?
>> > thanks
>> > David
>> >
>> > —
>> > You are receiving this because you modified the open/close state.
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/kikoso/Swipeable-Cards/issues/55#issuecomment-209327498
>> >
>> >
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kikoso/Swipeable-Cards/issues/55#issuecomment-209358150>
>>
>
>
>
> --
> http://www.davidmarchioni.fr
> Photographe
>



-- 
http://www.davidmarchioni.fr
Photographe

**Comment by lmouhib** [comment]
Hello

Apology for the delay. As I said earlier, I use a package called Ion which retrieve the picture from the URL. Below is the code to put in CardAdapter.java

    `@Override
    public View getCardView(int position, CardModel model, View convertView, ViewGroup parent) {
        ViewHolder holder = null;

        if (convertView == null) {
            convertView = LayoutInflater.from(getContext()).inflate(R.layout.card_layout, parent, false);
            assert convertView != null;

            holder = new ViewHolder();
            holder.gifImageView = (ImageView) convertView.findViewById(R.id.image);

            convertView.setTag(holder);
            ((TextView) convertView.findViewById(R.id.dweling_type)).setText(model.getDweling_type());
            ((TextView) convertView.findViewById(R.id.likes)).setText(model.getLikes());

        }

        Ion.with(getContext())
                .load(model.getImg_url())
                .withBitmap()
                .placeholder(R.mipmap.ic_launcher)
                .error(R.drawable.ic_message_white_24dp)
                .intoImageView(holder.gifImageView);

        return convertView;
    }`

In the CardModel, you change the Image from a bitmap to a string that will hold the URL.

This is the Package `com.koushikdutta.ion.Ion`

**Comment by davidm06** [comment]
Many Thanks
Thats cool I am just working on it
I'll keep you updated
regards

**Comment by davidm06** [comment]
hi *
many thanks
is it possible to reach you in private by mail ?

**Comment by davidm06** [comment]
Hi

It seems I do not have the same version of the initial 
SimpleCardStackAdapter.java
So I have error on ViewHolder when declaring ViewHolder holder = null;

Initial I have :

public final class SimpleCardStackAdapter extends CardStackAdapter {

     public SimpleCardStackAdapter(Context mContext) {
         super(mContext);
     }

     @Override
     public View getCardView(int position, CardModel model, View 
convertView, ViewGroup parent) {
         if(convertView == null) {
             LayoutInflater inflater = LayoutInflater.from(getContext());
             convertView = inflater.inflate(R.layout.std_card_inner, 
parent, false);
             assert convertView != null;
         }

         ((ImageView) 
convertView.findViewById(R.id.image)).setImageDrawable(model.getCardImageDrawable());
         ((TextView) 
convertView.findViewById(R.id.title)).setText(model.getTitle());
         ((TextView) 
convertView.findViewById(R.id.TxtMonGlop)).setText(model.getDescription());

         return convertView;
     }
}

**Comment by davidm06** [comment]
Hi again

I have an error on "ViewHolder holder = null;"
Error:(21, 3) error: cannot find symbol class ViewHolder
any idea ?
thanks

2016-04-15 13:55 GMT+02:00 lmouhib <notifications@github.com>:

> Hello
>
> Apology for the delay. As I said earlier, I use a package called Ion which
> retrieve the picture from the URL. Below is the code to put in
> CardAdapter.java
>
> `@Override
> public View getCardView(int position, CardModel model, View convertView, ViewGroup parent) {
>     ViewHolder holder = null;
>
>     if (convertView == null) {
>         convertView = LayoutInflater.from(getContext()).inflate(R.layout.card_layout, parent, false);
>         assert convertView != null;
>
>         holder = new ViewHolder();
>         holder.gifImageView = (ImageView) convertView.findViewById(R.id.image);
>
>         convertView.setTag(holder);
>         ((TextView) convertView.findViewById(R.id.dweling_type)).setText(model.getDweling_type());
>         ((TextView) convertView.findViewById(R.id.likes)).setText(model.getLikes());
>
>     }
>
>     Ion.with(getContext())
>             .load(model.getImg_url())
>             .withBitmap()
>             .placeholder(R.mipmap.ic_launcher)
>             .error(R.drawable.ic_message_white_24dp)
>             .intoImageView(holder.gifImageView);
>
>     return convertView;
> }`
>
> In the CardModel, you change the Image from a bitmap to a string that will
> hold the URL.
>
> This is the Package com.koushikdutta.ion.Ion
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/kikoso/Swipeable-Cards/issues/55#issuecomment-210437109>
>



-- 
http://www.davidmarchioni.fr
Photographe
