### ISSUE TITLE
How to show up hidden library in project structure?

### ISSUE THREAD

**Issue by datomnurdin** [kikoso/Swipeable-Cards#57]
I can't see your library after import via gradle

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.1.0'
    compile 'com.github.kikoso:SwipeableCards:1.1-RELEASE@aar'
}
```

![screen shot 2015-05-18 at 3 48 27 pm](https://cloud.githubusercontent.com/assets/5416242/7676340/02ca1f56-fd75-11e4-85e8-1fcc375bf72c.png)

Please advice. Thank you.

**Comment by kikoso** [comment]
The library is not being shown in the project structure, is downloaded as an artifact.
