### ISSUE TITLE
Get item position on card dismissed and click listeners.

### ISSUE THREAD

**Issue by rh0d0** [kikoso/Swipeable-Cards#7]

**Comment by faisalmemon1991** [comment]
How get the dismissed card ? I have added CardModel as parameter in onLike(CardModel c) and accessing it within it as c.getTitle().

But I am getting the first element only. Any idea on this?

**Comment by davidm06** [comment]
hi
did you get a solution ?
thanks

**Comment by kikoso** [comment]
Solved the issue with the first card

**Comment by TiagoGouvea** [comment]
I saw you change the line
    CardModel cardModel = (CardModel)getAdapter().getItem(getChildCount() - 1);
but to me, now, it aways getting the third next card on that line. 
I'm missing something?
