### ISSUE TITLE
error: cannot find symbol method getOnCardDimissedListener()

### ISSUE THREAD

**Issue by nadeemkhan** [kikoso/Swipeable-Cards#71]
hi i can't run AndTinderDemo please check attached screenshot for more understand the issue 
thanks.
![screen shot 2015-08-06 at 5 18 55 pm](https://cloud.githubusercontent.com/assets/1510017/9110923/76c728a8-3c5f-11e5-91f5-36a2cc9bc504.png)

**Comment by FarajiMehrdad** [comment]
me too!

**Comment by pengzhi** [comment]
getOnCardDimissedListener() - missing the 's' in 'Dimissed'

**Comment by kikoso** [comment]
Solved with https://github.com/kikoso/Swipeable-Cards/pull/70
