### ISSUE TITLE
UnsupportedOperationException 

### ISSUE THREAD

**Issue by parthivikky** [kikoso/Swipeable-Cards#86]
I was trying to implement this library into my project. I got the error "UnsupportedOperationException". I  don't know why, this exception occurred. I could not go ahead.

**Comment by palashgoel7** [comment]
I got the same error. My error existed in getSelectedView() function. I then commented out the line `throw new UnsupportedOperationException()`. It seems to work fine now.

**Comment by kikoso** [comment]
Fixed
